# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalisa.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 841, 608))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.play = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.play.setObjectName("play")
        self.gridLayout_7.addWidget(self.play, 0, 0, 1, 1)
        self.pause = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pause.setObjectName("pause")
        self.gridLayout_7.addWidget(self.pause, 0, 1, 1, 1)
        self.zoomin = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.zoomin.setObjectName("zoomin")
        self.gridLayout_7.addWidget(self.zoomin, 0, 2, 1, 1)
        self.zoomout = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.zoomout.setObjectName("zoomout")
        self.gridLayout_7.addWidget(self.zoomout, 0, 3, 1, 1)
        self.delete_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.delete_2.setObjectName("delete_2")
        self.gridLayout_7.addWidget(self.delete_2, 0, 4, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 804, 637))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.slider1 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.gridLayout_5.addWidget(self.slider1, 2, 0, 1, 1)
        self.channel1 = PlotWidget(self.scrollAreaWidgetContents_2)
        self.channel1.setObjectName("channel1")
        self.gridLayout_5.addWidget(self.channel1, 1, 0, 1, 1)
        self.checkbox1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkbox1.setObjectName("checkbox1")
        self.gridLayout_5.addWidget(self.checkbox1, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.channel2 = PlotWidget(self.scrollAreaWidgetContents_2)
        self.channel2.setObjectName("channel2")
        self.gridLayout_4.addWidget(self.channel2, 1, 0, 1, 1)
        self.slider2 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.gridLayout_4.addWidget(self.slider2, 2, 0, 1, 1)
        self.checkbox2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkbox2.setObjectName("checkbox2")
        self.gridLayout_4.addWidget(self.checkbox2, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.channel3 = PlotWidget(self.scrollAreaWidgetContents_2)
        self.channel3.setObjectName("channel3")
        self.gridLayout_3.addWidget(self.channel3, 1, 0, 1, 1)
        self.slider3 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.slider3.setOrientation(QtCore.Qt.Horizontal)
        self.slider3.setObjectName("slider3")
        self.gridLayout_3.addWidget(self.slider3, 2, 0, 1, 1)
        self.checkbox3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkbox3.setObjectName("checkbox3")
        self.gridLayout_3.addWidget(self.checkbox3, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.channel4 = PlotWidget(self.scrollAreaWidgetContents_2)
        self.channel4.setObjectName("channel4")
        self.gridLayout_2.addWidget(self.channel4, 1, 0, 1, 1)
        self.slider4 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.slider4.setOrientation(QtCore.Qt.Horizontal)
        self.slider4.setObjectName("slider4")
        self.gridLayout_2.addWidget(self.slider4, 2, 0, 1, 1)
        self.checkbox4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkbox4.setObjectName("checkbox4")
        self.gridLayout_2.addWidget(self.checkbox4, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.slider5 = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_2)
        self.slider5.setOrientation(QtCore.Qt.Horizontal)
        self.slider5.setObjectName("slider5")
        self.gridLayout.addWidget(self.slider5, 2, 0, 1, 1)
        self.channel5 = PlotWidget(self.scrollAreaWidgetContents_2)
        self.channel5.setObjectName("channel5")
        self.gridLayout.addWidget(self.channel5, 1, 0, 1, 1)
        self.checkbox5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkbox5.setObjectName("checkbox5")
        self.gridLayout.addWidget(self.checkbox5, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 4, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 1, 0, 1, 5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_8.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChannel_1 = QtWidgets.QAction(MainWindow)
        self.actionChannel_1.setObjectName("actionChannel_1")
        self.actionChannel_2 = QtWidgets.QAction(MainWindow)
        self.actionChannel_2.setObjectName("actionChannel_2")
        self.actionChannel_3 = QtWidgets.QAction(MainWindow)
        self.actionChannel_3.setObjectName("actionChannel_3")
        self.actionChannel_4 = QtWidgets.QAction(MainWindow)
        self.actionChannel_4.setObjectName("actionChannel_4")
        self.actionChannel_5 = QtWidgets.QAction(MainWindow)
        self.actionChannel_5.setObjectName("actionChannel_5")
        self.menuOpen.addAction(self.actionChannel_1)
        self.menuOpen.addAction(self.actionChannel_2)
        self.menuOpen.addAction(self.actionChannel_3)
        self.menuOpen.addAction(self.actionChannel_4)
        self.menuOpen.addAction(self.actionChannel_5)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.zoomin.setText(_translate("MainWindow", "Zoom In"))
        self.zoomout.setText(_translate("MainWindow", "Zoom Out"))
        self.delete_2.setText(_translate("MainWindow", "Delete"))
        self.checkbox1.setText(_translate("MainWindow", "Channel 1"))
        self.checkbox2.setText(_translate("MainWindow", "Channel 2"))
        self.checkbox3.setText(_translate("MainWindow", "Channel 3"))
        self.checkbox4.setText(_translate("MainWindow", "Channel 4"))
        self.checkbox5.setText(_translate("MainWindow", "Channel 5"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionChannel_1.setText(_translate("MainWindow", "Channel 1"))
        self.actionChannel_2.setText(_translate("MainWindow", "Channel 2"))
        self.actionChannel_3.setText(_translate("MainWindow", "Channel 3"))
        self.actionChannel_4.setText(_translate("MainWindow", "Channel 4"))
        self.actionChannel_5.setText(_translate("MainWindow", "Channel 5"))
from pyqtgraph import PlotWidget
